### ISSUE TITLE
Broken link in docs 

### ISSUE THREAD

**Issue by ptim** [domino-team/docs#1]
Hi :) 

There's a broken link from the getting started page:

"Go to the **Domino Pi** hardware for more details of the hardware."

http://domino.io/docs/hardware/pi/

> The requested URL /docs/hardware/pi.html/ was not found on this server.

(PS the packaging didn't bother me!) Cheers, Tim

**Comment by alzhao** [comment]
removed this link temporary. There will be some links missing too. To view in good format, view it on http://domino.io/docs. Thanks

**Comment by cyrt63** [comment]
Hello, blank page : http://domino.io/#!domino/domino/pi/pi.md
Regards
