### ISSUE TITLE
I'm stuck. Docs do not sufficiently detail how to connect to a new Domino Pi

### ISSUE THREAD

**Issue by gruvin** [domino-team/docs#2]
Hello

I just received my Domino Pi and bit, from the Kickstarter campaign. Thanks :-) Only, I am not able to do anything with it.

This appears to be the only place available to access any kind of genuine support from the Domino team, at this time.

I have read the available documentation. In essence, it says to plug things together, boot up the Domino Pi and then visit http://domino.local to access the WebUI. Unsurprisingly, this does not work, for the following reasons IMO ...
1. There is no mechanism I know of that could allow domino.local appear as a resolvable URN on my network, unless maybe if I was connected to the 'Pi as an access point, which I cannot.  See 3, below.
2. Whilst both the LAN LEDs come on (depending which port I connect Ethernet to) my DHCP server does not issue an IP address. Ordinarily, this can only mean that the DHCP server was not asked for an IP in the first place.
3. A new WiFi network access point does appear, with SSID "Domino-280". However, there is no mention anywhere in the documentation to tell us the default password. (I assume it's WPA2?)

Would someone be so kind as to update this documentation just a tiny it, to include the details needed to get past this first and rather significant hurdle? Thanks.

Oh ... I had a brief look on the WRT website. But that's a huge resource, covering many, many devices. I could not find anything much specifically related to the Domino, other than the original Kickstarter announcement and spreads of 'random' discussion, which with respect, I simply do not have the time or energy to wade through, for only a slim chance of finding answers to the above.

Kind Regards,

Bryan J. Rentoul
Upper Hutt, New Zealand

**Comment by xyb** [comment]
Hi, Rentoul, as a Domino user, I recommend using the [github docs project](https://github.com/domino-team/docs) as your firsthand data. The default password is: `googdlife`, you can check it on the [using](https://github.com/domino-team/docs/blob/master/pi/using.md) docs.

**Comment by gruvin** [comment]
Hello xyb. Thanks for the answer! The AP password worked for me.

I read that this very GitHub project (the one I am commenting on here) is the source of the domino.io documentation. Therefore, I did not dig deeper into the GitHub version of docs, since I have already read all of the available documentation at domino.io/docs.

**Comment by gruvin** [comment]
I checked again. The README.md file of this domino-team/docs GitHub repository explicitly states ...

"Domino Documentation is hosted on github. You can view this on both github and domino.io/docs/"

And yet, the documentation in this GitHub domino-team/docs repository bears very little similarity to the docs at http://domino.io/docs. 

Very confused. 

But at least I know where the real docs are now. Thanks again.

**Comment by alzhao** [comment]
The docs on github and domino.io/doc are the same, as domino.io/docs only
makes a pull request from github. But it looks very difficult. On github
they are md files. While on domino.io/docs they are transferred into html.
If you narrow down your browser to view the docs, you will find they are
the same as in github.

**Comment by gruvin** [comment]
I think I've worked it out. The repository here has a pi/using.md file, containing the, "missing" information. Full URL https://github.com/domino-team/docs/blob/master/pi/using.md

But it seems that page is not linked from any other page in the docs tree.

There is a short "USING DOMINO PI" text section at the bottom of http://domino.io/docs/pi/. But no link to the all important using.md HTML file.

**Comment by Squonk42** [comment]
Thanks @gruvin, it was in the nav list, but I agree it was not obvious to find. I added the missing link to the "Using Domino Pi" section as you suggested!
