### ISSUE TITLE
Repeater Reset leaves router unable to setup a new WISP session

### ISSUE THREAD

**Issue by goojo** [domino-team/docs#4]
I tried the WISP reset script:
http://www.gl-inet.com/docs/wiki/#!mini/repeater.md

After a reset I was able to see Wifi again (as expected,  then I joined new master AP) 

Now even after a reboot I was unable to make a connection to the internet, the wlan0 was in a disabled state. 

Doing:
uci -q set wireless.sta.disabled=0

but I was unable to establish a new connection via the web interface.

Adding a new wireless connection in the WebUI may not be setting disabled back to 0?

**Comment by alzhao** [comment]
@goojo sorry for missing this thread. This problem is fixed in recent firmware update v2.22.
