### ISSUE TITLE
modifying uboot to not read ttyS0

### ISSUE THREAD

**Issue by vavrecan** [domino-team/docs#6]
I was wondering what would be the easiest way to change uboot not to use serial port RX input (ttyS0). 
I would like to use serial port to read data from external device (which is sending a lot of text data all time), however, if I reboot one of the mini routers, either GL-AR150 or GL-AR300M, uboot gets invalid input and it will not continue booting.

Any ideas? Thank you

**Comment by alzhao** [comment]
First it is not good to disable console in uboot, because it is risky that you will never be able to enter uboot again.
Second, the solution for this is to use combined input in uboot in order to stop it. Now you can just use any key to stop uboot, so your router will always not boot. But you can change this to a combination. We have done this before and use "gl" to stop uboot. Generally this is more enough to let the system boot.
So question is: what is the model you are using?

**Comment by vavrecan** [comment]
that would be great! :+1:  I am using both gl-ar150 (mainly) and gl-ar300m (testing) - do you think you could provide tutorials how to do it for both?

**Comment by alzhao** [comment]
yes. I can provide you uboot for ar150 first, as this is what we knows better. The uboot for AR300M is very different

**Comment by vavrecan** [comment]
sure, that sounds good! :+1:  is it easy process to overwrite uboot?

**Comment by alzhao** [comment]
It is easy, but always risky. Even small probability for bricking is killing...

**Comment by vavrecan** [comment]
willing to take the risk :+1:  
do you think you could add simple steps (from uboot compilation and so on)? Thanks

**Comment by alzhao** [comment]
Actually https://github.com/domino-team/uboot-domino is the uboot you want. In this uboot, you need to type "gl" to stop in uboot console. Still need to write a very detail instructions.

**Comment by vavrecan** [comment]
thank you - that looks great. I see that you can modify this by changing CONFIG_AUTOBOOT_STOP_STR to specify custom stop string. 

looking forward to the instructions - I just wonder how to flash it correctly

**Comment by alzhao** [comment]
The general process of changing uboot is:

connect to router using USB uart adapter
enter uboot console
setup a tftp server
run command run lu
Please refer to http://www.gl-inet.com/docs/diy/uboot/ for more details.
