### ISSUE TITLE
uboot modifications source for gl-ar300m

### ISSUE THREAD

**Issue by vavrecan** [domino-team/docs#8]
Hello,
I was wondering what kind of uboot are you using for the gl-ar300m - did you made any modifications into it? what version are you using? 
Thanks a lot!

**Comment by vavrecan** [comment]
it seems that my version is using U-Boot 1.1.4-g87b46363-dirty - I am wondering - did you added Qualcomm Atheros SPI NAND Driver into it?

**Comment by vavrecan** [comment]
Any updates?

**Comment by alzhao** [comment]
Yes, of course there is nand driver in uboot. Otherwise it cannot recognize nand flash.

**Comment by vavrecan** [comment]
can you please provide source of the uboot you are using? 
Thanks

**Comment by alzhao** [comment]
I don't want to release the code publicly but I can send you a copy privately. Just send me a private email alzhao at gl-inet.com
